more logging

diff --git a/bash-web-server b/bash-web-server
--- a/bash-web-server
+++ b/bash-web-server
@@ -230,11 +230,11 @@ process-request() {
 
 	# validate the request
 	[[ ${REQ_INFO[version]} == 'HTTP/1.1' ]] \
-	    || fatal 'unsupported HTTP version'
+		|| fatal "unsupported HTTP version: '${REQ_INFO[version]}'"
 	[[ ${REQ_INFO[method]} == 'GET' ]] \
-	    || fatal 'unsupported HTTP method'
+		|| fatal "unsupported HTTP method: '${REQ_INFO[method]}'"
 	[[ ${REQ_INFO[path]} == /* ]] \
-	    || fatal 'path must be absolute'
+		|| fatal 'path must be absolute'
 
 	echo "${REQ_INFO[method]} ${REQ_INFO[path]}"
 
@@ -280,6 +280,7 @@ process-request() {
 		local mime
 		mime=$(mime-type "$file")
 
+		echo "  serving file '$file'"
 		printf 'HTTP/1.1 200 OK\r\n' >&"$fd"
 		printf 'Content-Type: %s\r\n' "$mime" >&"$fd"
 		printf '\r\n' >&"$fd"
@@ -287,6 +288,7 @@ process-request() {
 	elif [[ -d $path ]]; then
 		# redirect to /path/ if directory requested without trailing slash
 		if [[ ${REQ_INFO[path]} != */ ]]; then
+			echo "  serving redirect '${REQ_INFO[path]}'"
 			printf 'HTTP/1.1 301 Moved Permanently\r\n' >&"$fd"
 			printf 'Location: %s/\r\n' "${REQ_INFO[path]}" >&"$fd"
 			printf '\r\n' >&"$fd"
@@ -294,12 +296,14 @@ process-request() {
 		fi
 
 		# try a directory listing
+		echo "  serving dir listing '$path'"
 		printf 'HTTP/1.1 200 OK\r\n' >&"$fd"
 		printf 'Content-Type: text/html; charset=utf-8\r\n' >&"$fd"
 		printf '\r\n' >&"$fd"
 		list-directory "$path" >&"$fd"
 	else
 		# nothing was found
+		echo '  serving nothing'
 		printf 'HTTP/1.1 404 Not Found\r\n' >&"$fd"
 		printf '\r\n' >&"$fd"
 	fi
@@ -321,15 +325,15 @@ main() {
 		esac
 	done
 
-	cd "$DIR" || fatal "failed to move to $DIR"
+	cd "$DIR" || fatal "failed to move to '$DIR'"
 
 	echo "listening on http://$ADDRESS:$PORT"
-	echo "serving out of $PWD"
+	echo "serving out of '$PWD'"
 
 	local fd ip
 	while true; do
 		accept -b "$ADDRESS" -v fd -r ip "$PORT" \
-		    || fatal 'failed to read socket'
+			|| fatal 'failed to read socket'
 		process-request "$fd" &
 
 		exec {fd}>&-
